conv_layers:
- activation: relu
  filters: 32
  input_shape:
  - 224
  - 224
  - 3
  kernel_size:
  - 3
  - 3
- activation: relu
  filters: 32
  input_shape:
  - 224
  - 224
  - 3
  kernel_size:
  - 3
  - 3
dense_layers:
  activation: relu
  units: 512
fine_tuning:
  fine_tune_at: 100
  fine_tune_epochs: 10
  learning_rate: 0.001
  loss: BinaryCrossentropy
  metrics:
    name: BinaryAccuracy
    params:
      name: accuracy
      threshold: 0.5
  optimizer: RMSprop
generators:
  fill_mode: nearest
  height_shift_range: 0.2
  rescale: 0.00392156862745098
  rotation_range: 40
  shear_range: 0.2
  width_shift_range: 0.2
  zoom_range: 0.2
info:
  classes:
  - REAL
  - FAKE
  finetune_filepath: ../output/cifake_tf_ft.h5
  finetune_history_filepath: ../output/history_cifake_tf_ft.pkl
  history_filepath: ../output/history_cifake_tf.pkl
  model_filepath: ../output/cifake_tf.h5
  model_name: tf
  test_dir: ../input/images/test
  train_dir: ../input/images/train
  validation_dir: ../input/images/validation
maxpool_layers:
  pool_size:
  - 2
  - 2
model:
  dropout: 0.5
  epochs: 20
  loss: categorical_crossentropy
  metrics:
  - accuracy
  optimizer: adam
  steps_per_epoch: 25
  validation_steps: 23
output_layer:
  activation: softmax
  units: 2
preprocess:
  normalize: 255
  resize:
  - 224
  - 224
transfer_learning:
  initial_epochs: 10
  learning_rate: 0.001
  loss: BinaryCrossentropy
  metrics:
    name: BinaryAccuracy
    params:
      name: accuracy
      threshold: 0.5
  optimizer: Adam
